### ISSUE TITLE
请问有办法让它支持 MathJax 3 吗

### ISSUE THREAD

**Issue by KotobaTrilius** [Mybrc91/hexo-renderer-mathjax2#2]
MathJax 已经更新到 3.1.4 了，但是这个好像还停留在 2 的版本，更改 src 好像不起作用

**Comment by Mybrc91** [comment]
> MathJax 已经更新到 3.1.4 了，但是这个好像还停留在 2 的版本，更改 src 好像不起作用

好，我试试

**Comment by Mybrc91** [comment]
> MathJax 已经更新到 3.1.4 了，但是这个好像还停留在 2 的版本，更改 src 好像不起作用

可以了，你可以用mathjax3分支的代码测试一下
